name: package-cleanup

on:
  registry_package:
    types: published

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with: 
          package-name: 'com.tn.tn-parent'
          package-type: 'maven'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "true"
      - uses: actions/delete-package-versions@v5
        with: 
          package-name: 'com.tn.tn-lang'
          package-type: 'maven'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "true"    
